import { readFile, mkdir, writeFile, rename, rm, access } from 'node:fs/promises';
import { resolve, dirname, join, relative } from 'node:path';
import { z } from 'zod';
import puppeteer from 'puppeteer';
import { buildPublication } from '../modules/publication.ts';
import { parseFile } from '../modules/project.ts';
const [configPath, outputPath] = process.argv.slice(2);
if (!configPath || !outputPath)
  throw Error('Usage: npm run publish:corpus -- corpus.json output-directory');
const path = resolve(configPath),
  root = dirname(path),
  out = resolve(outputPath);
const config = z
  .object({
    title: z.object({ en: z.string(), zh: z.string() }),
    baseURL: z.string().url(),
    editorURL: z.string().url(),
    documents: z.array(z.string()),
    asOf: z.string().optional(),
  })
  .strict()
  .parse(JSON.parse(await readFile(path, 'utf8')));
for (const input of [path, ...config.documents.map((p) => resolve(root, p))]) {
  const r = relative(out, input);
  if (!r.startsWith('..'))
    throw Error('Output cannot contain source documents or the corpus configuration.');
}
const exists = async (p: string) =>
  access(p).then(
    () => true,
    () => false,
  );
if ((await exists(out)) && !(await exists(join(out, '.style-guide-generated'))))
  throw Error(
    'Refusing to replace a directory not marked as generated output. Choose an empty output path.',
  );
const projects = await Promise.all(
  config.documents.map(async (p) => parseFile(await readFile(resolve(root, p), 'utf8'))),
);
const logo =
  'data:image/png;base64,' +
  (
    await readFile(new URL('../assets/branding/lifehouse-hong-kong-stacked.png', import.meta.url))
  ).toString('base64');
const build = await buildPublication(projects, { ...config, logo });
const staging = out + '.staging-' + crypto.randomUUID(),
  backup = out + '.previous-' + crypto.randomUUID();
await mkdir(staging, { recursive: true });
try {
  for (const [path, text] of Object.entries(build.files)) {
    const target = join(staging, path);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, text);
  }
  if (Object.keys(build.pdfPages).length) {
    const browser = await puppeteer.launch({ args: process.env.CI ? ['--no-sandbox'] : [] });
    try {
      for (const [path, html] of Object.entries(build.pdfPages)) {
        const page = await browser.newPage();
        await page.setContent(html, { waitUntil: 'load' });
        await page.evaluate(async () => {
          await document.fonts.ready;
          await Promise.all([...document.images].map((i) => i.decode()));
        });
        await page.pdf({
          path: join(staging, path),
          preferCSSPageSize: true,
          printBackground: true,
          tagged: true,
          outline: true,
        });
        await page.close();
      }
    } finally {
      await browser.close();
    }
  }
  await writeFile(join(staging, '.style-guide-generated'), 'Generated by Style Guide Studio\n');
  const old = await exists(out);
  if (old) await rename(out, backup);
  try {
    await rename(staging, out);
  } catch (e) {
    if (old) await rename(backup, out);
    throw e;
  }
  if (old) await rm(backup, { recursive: true });
  console.log(
    `Built ${projects.length} source documents, ${Object.keys(build.files).length} static files and ${Object.keys(build.pdfPages).length} PDFs in ${out}.`,
  );
} catch (e) {
  await rm(staging, { recursive: true, force: true });
  throw e;
}
